const GET_INTEGRATIONS_REQUEST = 'GET_INTEGRATIONS_REQUEST';
const GET_INTEGRATIONS_SUCCESS = 'GET_INTEGRATIONS_SUCCESS';
const GET_INTEGRATIONS_FAIL = 'GET_INTEGRATIONS_FAIL';

export default {
    GET_INTEGRATIONS_REQUEST,
    GET_INTEGRATIONS_SUCCESS,
    GET_INTEGRATIONS_FAIL,
}