const CREATE_INTEGRATION_REQUEST = 'CREATE_INTEGRATION_REQUEST';
const CREATE_INTEGRATION_FAIL = 'CREATE_INTEGRATION_FAIL';
const GET_INTEGRATION_REQUEST = 'GET_INTEGRATION_REQUEST';
const GET_INTEGRATION_SUCCESS = 'GET_INTEGRATION_SUCCESS';


export default {
    CREATE_INTEGRATION_REQUEST,
    CREATE_INTEGRATION_FAIL,
    GET_INTEGRATION_REQUEST,
    GET_INTEGRATION_SUCCESS,
}